apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ .Release.Name }}-ingress
spec:
  rules:
    - host: dummy-ab.ab
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-dummy-ab
                port:
                  name: http
    - host: dummy-a.ab
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-dummy-a
                port:
                  name: http
    - host: dummy-b.ab
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-dummy-b
                port:
                  name: http
