eck-elasticsearch:
  enabled: true
  annotations:
    eck.k8s.elastic.co/license: basic
eck-kibana:
  enabled: true
  annotations:
    eck.k8s.elastic.co/license: basic
  spec:
    http:
      tls:
        selfSignedCertificate:
          disabled: true
eck-agent.enabled: false
eck-fleet-server.enabled: false
eck-beats.enabled: false