apiVersion: apps/v1
kind: Deployment
metadata:
  name: dummy-a
  labels:
    app: dummy-a
spec:
  selector:
    matchLabels:
      app: dummy-a
  template:
    metadata:
      labels:
        app: dummy-a
    spec:
      containers:
        - name: dummy-a
          image: ghcr.io/psieniawski/dummy-a
          imagePullPolicy: Always
          ports:
            - containerPort: 9001
          env:
            - name: BPL_JVM_THREAD_COUNT
              value: "50"
#            - name: SPRING_DATASOURCE_URL
#              value: jdbc:postgresql://polar-postgres/polardb_catalog
#            - name: SPRING_PROFILES_ACTIVE
#              value: testdata
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dummy-b
  labels:
    app: dummy-b
spec:
  selector:
    matchLabels:
      app: dummy-b
  template:
    metadata:
      labels:
        app: dummy-b
    spec:
      containers:
        - name: dummy-b
          image: ghcr.io/psieniawski/dummy-b
          imagePullPolicy: Always
          ports:
            - containerPort: 9001
          env:
            - name: BPL_JVM_THREAD_COUNT
              value: "50"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dummy-ab
  labels:
    app: dummy-ab
spec:
  selector:
    matchLabels:
      app: dummy-ab
  template:
    metadata:
      labels:
        app: dummy-ab
    spec:
      containers:
        - name: dummy-ab
          image: ghcr.io/psieniawski/dummy-ab
          imagePullPolicy: Always
          ports:
            - containerPort: 9001
          env:
            - name: BPL_JVM_THREAD_COUNT
              value: "50"
            - name: dummy-a_serviceUri
              value: http://dummy-a-service:9001
            - name: dummy-b_serviceUri
              value: http://dummy-b-service:9001
