apiVersion: apps/v1
kind: Deployment
metadata:
  name: dummy-a
  labels:
    app: dummy
spec:
  selector:
    matchLabels:
      app: dummy
  template:
    metadata:
      labels:
        app: dummy
    spec:
      containers:
        - name: dummy-a
          image: ghcr.io/psieniawski/dummy-a
          imagePullPolicy: Always
          ports:
            - containerPort: 9001
          env:
            - name: BPL_JVM_THREAD_COUNT
              value: "50"
#            - name: SPRING_DATASOURCE_URL
#              value: jdbc:postgresql://polar-postgres/polardb_catalog
#            - name: SPRING_PROFILES_ACTIVE
#              value: testdata
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dummy-b
  labels:
    app: dummy
spec:
  selector:
    matchLabels:
      app: dummy
  template:
    metadata:
      labels:
        app: dummy
    spec:
      containers:
        - name: dummy-b
          image: ghcr.io/psieniawski/dummy-b
          imagePullPolicy: Always
          ports:
            - containerPort: 9001
          env:
            - name: BPL_JVM_THREAD_COUNT
              value: "50"