#debug: true
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
#      details are part of components, so enabling them enables also the components
#      show-components: always
      probes:
        # default on Kubernetes
        enabled: true
    shutdown:
      enabled: true
  info:
    java:
      enabled: true
    os:
      enabled: true
  metrics:
    tags:
      app: ${app.name}
    distribution:
#      slo:
#        http:
#          server:
#            requests: 25ms, 50ms, 100ms, 200ms, 400ms, 800ms

      percentiles-histogram:
        http:
          server:
            requests: true
#      minimum-expected-value:
#        http:
#          server:
#            requests: 0.05
#      maximum-expected-value:
#        http:
#          server:
#            requests: 0.8


#      percentiles:
#        http:
#          server:
#            requests: 0.5, 0.9, 0.95, 0.99, 0.999


server:
  port: 9001
  tomcat:
    connection-timeout: 2s
    keep-alive-timeout: 15s
    threads:
      max: 50
      min-spare: 5
  shutdown: graceful
spring:
  lifecycle:
    timeout-per-shutdown-phase: 15s
#logging:
#  pattern:
#  level:
#    ab: info
