version: '3'
services:
  dummy-a-service:
    image: ghcr.io/psieniawski/dummy-a:latest
    container_name: dummy-a
    restart: on-failure
    environment:
      debug: false
    ports:
      - "8080:9001"
    networks:
      dummy:
    healthcheck:
      test: "wget --no-cache --spider http://localhost:9001/actuator/health || exit 1"
      interval: 5s
      timeout: 10s
      #      start_period: 10s
      retries: 10
  dummy-b-service:
    image: ghcr.io/psieniawski/dummy-b:latest
    container_name: dummy-b
    restart: on-failure
    environment:
      debug: false
    ports:
      - "8081:9001"
    networks:
      dummy:
    healthcheck:
      test: "wget --no-cache --spider http://localhost:9001/actuator/health || exit 1"
      interval: 5s
      timeout: 10s
      #      start_period: 10s
      retries: 10
  dummy-ab-service:
    image: ghcr.io/psieniawski/dummy-ab:latest
    container_name: dummy-ab
    restart: on-failure
    environment:
      debug: false
      dummy-a_serviceUri: http://dummy-a-service:9001
      dummy-b_serviceUri: http://dummy-b-service:9001
    ports:
      - "9001:9001"
    networks:
      dummy:
    healthcheck:
      test: "wget --no-cache --spider http://localhost:9001/actuator/health || exit 1"
      interval: 5s
      timeout: 10s
      #      start_period: 10s
      retries: 10

networks:
  dummy:
