name: Commit Stage
on: push

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      security-events: write
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
          cache: gradle
      - name: Validate Kubernetes manifests
        uses: stefanprodan/kube-tools@v1
        with:
          kubectl: 1.23.4
          kubeval: 0.16.1
          command: |
            kubeval --strict --ignore-missing-schemas -d k8s/ab
      - name: Code vulnerability scanning
        uses: anchore/scan-action@v3
        id: scan
        with:
          path: "${{ github.workspace }}"
          fail-build: false
          severity-cutoff: high
          output-format: sarif
      - name: Upload vulnerability report
        uses: github/codeql-action/upload-sarif@v2
        if: success() || failure()
        with:
          sarif_file: ${{ steps.scan.outputs.sarif }}
      - name: Build, unit tests and integration tests
        run: |
          chmod +x gradlew
          ./gradlew build
  package-dummy-a:
    uses: ./.github/workflows/package.yml
    if: ${{ github.ref == 'refs/heads/main' }}
    needs: [ build ]
    with:
      image-name: dummy-a
      gradle-task: ':dummy-a:boot-app:bootBuildImage'
  package-dummy-b:
    uses: ./.github/workflows/package.yml
    if: ${{ github.ref == 'refs/heads/main' }}
    needs: [ build ]
    with:
      image-name: dummy-b
      gradle-task: ':dummy-b:boot-app:bootBuildImage'
  package-dummy-ab:
    uses: ./.github/workflows/package.yml
    if: ${{ github.ref == 'refs/heads/main' }}
    needs: [ build ]
    with:
      image-name: dummy-ab
      gradle-task: ':dummy-ab:boot-app:bootBuildImage'
